# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Ricette"
 pageRef = "ricette"
 weight = 20

[[main]]
 name = "Primi"
 parent = "Ricette"
 pageRef = "/tags/primi"
 weight = 10

[[main]]
 name = "Secondi"
 parent = "Ricette"
 pageRef = "/tags/secondi"
 weight = 20

[[main]]
 name = "Contorni"
 parent = "Ricette"
 pageRef = "/tags/contorni"
 weight = 20

[[main]]
 name = "Dessert"
 parent = "Ricette"
 pageRef = "/tags/dessert"
 weight = 30

[[subnavigation]]
 name = "15 Minuti"
 pageRef = "/tags/15m"
 weight = 10

[[subnavigation]]
 name = "30 Minuti"
 pageRef = "/tags/30m"
 weight = 20

[[subnavigation]]
 name = "45 Minuti"
 pageRef = "/tags/45m"
 weight = 30

[[subnavigation]]
 name = "60 Minuti"
 pageRef = "/tags/60m"
 weight = 40


#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

[[main]]
 name = "About"
 pageRef = "about"
 weight = 30

# [[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20
